// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKjEj0qmH9tFlQBdrMfFF3LH6SuTajIE',
    appId: '1:587070276095:web:84e3478bb164e9653167ca',
    messagingSenderId: '587070276095',
    projectId: 'chat-app-da7eb',
    authDomain: 'chat-app-da7eb.firebaseapp.com',
    storageBucket: 'chat-app-da7eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGbHQhjaqSEQYiG5hmMYm_a0xfqj7fRm8',
    appId: '1:587070276095:android:79e04bb4a0e655003167ca',
    messagingSenderId: '587070276095',
    projectId: 'chat-app-da7eb',
    storageBucket: 'chat-app-da7eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPnS2KOTRbCN05hMxFLiroezqFiNtaz8',
    appId: '1:587070276095:ios:d30b84d9ab7d23083167ca',
    messagingSenderId: '587070276095',
    projectId: 'chat-app-da7eb',
    storageBucket: 'chat-app-da7eb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPnS2KOTRbCN05hMxFLiroezqFiNtaz8',
    appId: '1:587070276095:ios:d30b84d9ab7d23083167ca',
    messagingSenderId: '587070276095',
    projectId: 'chat-app-da7eb',
    storageBucket: 'chat-app-da7eb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDKjEj0qmH9tFlQBdrMfFF3LH6SuTajIE',
    appId: '1:587070276095:web:08444f617d2542613167ca',
    messagingSenderId: '587070276095',
    projectId: 'chat-app-da7eb',
    authDomain: 'chat-app-da7eb.firebaseapp.com',
    storageBucket: 'chat-app-da7eb.appspot.com',
  );
}
